fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.19.0
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd.git
    file_capability:
      repo: https://github.com/smoeding/puppet-file_capability.git
  symlinks:
    nfsroot: "#{source_dir}"
    hieradata: "#{File.join(source_dir, '../../data')}"
    osc: "#{File.join(source_dir, '../osc')}"
